### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by javierbrea** [mocks-server/main#157]
In some projects, the package returns an error due to an installation bug:

```
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- /Users/javierbrea/proyectos/data-provider/axios/node_modules/ajv-errors/dist/index.js
- /Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/core/src/mocks/validations.js
- /Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/core/src/mocks/Mock.js
- /Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/core/src/mocks/helpers.js
- /Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/core/src/mocks/Mocks.js
- /Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/core/src/Core.js
- /Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/core/index.js
- /Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/main/lib/start.js
- /Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/main/bin/mocks-server
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/javierbrea/proyectos/data-provider/axios/node_modules/ajv-errors/dist/index.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/javierbrea/proyectos/data-provider/axios/node_modules/ajv-errors/dist/index.js',
    '/Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/core/src/mocks/validations.js',
    '/Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/core/src/mocks/Mock.js',
    '/Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/core/src/mocks/helpers.js',
    '/Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/core/src/mocks/Mocks.js',
    '/Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/core/src/Core.js',
    '/Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/core/index.js',
    '/Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/main/lib/start.js',
    '/Users/javierbrea/proyectos/data-provider/axios/node_modules/@mocks-server/main/bin/mocks-server'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by javierbrea** [comment]
It seems to be related to [this similar issue found on serverless](https://github.com/serverless/serverless/issues/8727).  Possible solutions are [here](https://github.com/serverless/serverless/issues/8727#issuecomment-757892958). A note should be added to the installation docs providing this workaround, and another one found by me that consists in modifiying manually the `package-lock.json` file, adding the `ajv-errors` dependency to `mocks-server`:

```jsonc
"ajv-errors": {
  "version": "3.0.0",
  "resolved": "https://registry.npmjs.org/ajv-errors/-/ajv-errors-3.0.0.tgz",
  "integrity": "sha512-V3wD15YHfHz6y0KdhYFjyy9vWtEVALT9UrxfN3zqlI6dMioHnJrqOYfyPKol3oqrnCM9uwkcdCwkJ0WUcbLMTQ==",
  "dev": true
}
```
