### ISSUE TITLE
JavaScript API: createServer command with config object throws error "unknown option '--config'"

### ISSUE THREAD

**Issue by y7haar** [mocks-server/main#488]
**Describe the bug**
When using the command `createServer` with a given config object, mocks server always crashes and throws the error:

``` 
error: unknown option '--config'
  ●  process.exit called with "1"
      at Command._exit (node_modules/@mocks-server/config/node_modules/commander/lib/command.js:458:13)
      at Command._displayError (node_modules/@mocks-server/config/node_modules/commander/lib/command.js:1466:10)
      at Command.unknownOption (node_modules/@mocks-server/config/node_modules/commander/lib/command.js:1555:10)
      at checkForUnknownOptions (node_modules/@mocks-server/config/node_modules/commander/lib/command.js:1216:14)
      at Command._parseCommand (node_modules/@mocks-server/config/node_modules/commander/lib/command.js:1254:7)
      at Command.parse (node_modules/@mocks-server/config/node_modules/commander/lib/command.js:897:10)
      at CommandLineArguments.read (node_modules/@mocks-server/config/src/CommandLineArguments.js:119:13)
      at Config._loadFromArgs (node_modules/@mocks-server/config/src/Config.js:113:23)
      at Config._load (node_modules/@mocks-server/config/src/Config.js:165:35)
      at Config.load (node_modules/@mocks-server/config/src/Config.js:187:16)
      at Core._loadConfig (node_modules/@mocks-server/core/src/Core.js:154:24)
      at Core.init (node_modules/@mocks-server/core/src/Core.js:199:16)
      at Core.start (node_modules/@mocks-server/core/src/Core.js:209:5)
``` 

**To Reproduce**

- create some dummy fixtures / routes and collections inside the mocks directory
-  create and start a mocks server instance with the following snippet (this is taken from the official docs: https://www.mocks-server.org/docs/api/javascript/):

``` 
const core = createServer({
      config: {
        readArguments: true,
        readEnvironment: true,
        readFile: true,
      },
      plugins: {
        inquirerCli: {
          enabled: true,
        },
      },
      files: {
        enabled: true,
      },
    });

core.start();
``` 

**Expected behavior**
Mocks Server should start and load all routes from the mocks directory as described in the docs.

** Operating system, Node.js an npm versions, or browser version (please complete the following information):**
 - OS: macOS 13.2.1
 - Node.js: v16.20.2
 - npm: 8.19.4
 - Browser: React Native App, iOS and android

**Comment by javierbrea** [comment]
Hi @y7haar , when you enable the mock server to readArguments, it validates by default that all arguments are valid, and it throws an error in case not. So, you are probably passing a `--config` argument to your command, and that produces the error.

You have some options to avoid this:

* Disable the server to read arguments from the command line. Given that you are going to start it programmatically, probably you don't need to configure it by using arguments. You can disable it by changing the `config.readArguments` option to `false`. You should also disable options for reading environment vars and config file in case you neither need them.
  ```js
  createServer({
      config: {
        readArguments: false,
        readEnvironment: true,
        readFile: true,
      },
   ```
* Allow unknown arguments by using the `config.allowUnknownArguments` option. This will allow you to set the server options through command arguments, but it will not throw error on unknown arguments.
   ```js
  createServer({
      config: {
        readArguments: true,
        allowUnknownArguments: true,
        readEnvironment: true,
        readFile: true,
      },
   ```

You can [read more about server configuration here](https://www.mocks-server.org/docs/configuration/how-to-change-settings/)

**Comment by y7haar** [comment]
Hi @javierbrea, thanks for your quick response! Setting `readArguments` to `false` did the trick. 

We're using mocks-server together with detox to test our react native app. The initialization of mocks-server happens inside the detox context, maybe this is why the error occurred.
